<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegistrantTypeOftheuserInMyMeetingspage</name>
   <tag></tag>
   <elementGuidId>e23d8a0b-6301-452a-84df-12bfed153cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;conventions-session-detail__attendees&quot;]//table//td[text()=&quot;${EMAIL}&quot;]/..//td[text()=&quot;${RgistrantType}&quot;}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
