<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyRegistrantTypeOftheUserInLiveSessionsPage</name>
   <tag></tag>
   <elementGuidId>f530ecc5-af77-498d-83cf-2fc1be38a69f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;conventions-session-detail__attendees&quot;]//table//td[text()=&quot;${EMAIL}&quot;]/..//td[text()=&quot;${RgistrantType}&quot;}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
